config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    //$routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/register', ['controller' => 'users', 'action' => 'register'])->setMiddleware(['csrf']);
    $routes->connect('/verification', ['controller' => 'users', 'action' => 'verification']);
    $routes->connect('/login', ['controller' => 'users', 'action' => 'login']);
    $routes->connect('/logout', ['controller' => 'users', 'action' => 'logout']);
    $routes->connect('/user/view', ['controller' => 'users', 'action' => 'view']);
    $routes->connect('/users/search', ['controller' => 'users', 'action' => 'search']);

    $routes->connect('/', ['controller' => 'users', 'action' => 'login']);
    $routes->connect('/posts/index', ['controller' => 'posts', 'action' => 'add']);
    $routes->connect('/posts/add', ['controller' => 'posts', 'action' => 'add']);
    $routes->connect('/posts/edit', ['controller' => 'posts', 'action' => 'edit']);
    $routes->connect('/posts/delete', ['controller' => 'posts', 'action' => 'delete']);
    $routes->connect('/comments/add', ['controller' => 'comments', 'action' => 'add']);
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    //$routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Post.php
<?php
// src/Model/Entity/Post.php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class Post extends Entity
{
    protected $_accessible = [
        '*' => true,
        'id' => false,
        'slug' => false,
    ];
}

src/Model/Table/PostsTable.php
<?php
// src/Model/Table/PostsTable.php
namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;

class PostsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        $this->addBehavior('Timestamp');
        $this->belongsTo('Users', [
            'className' => 'Users',
            'foreignKey' => 'user_id'
        ]);
        $this->belongsTo('Retweets', [
            'className' => 'Posts',
            'foreignKey' => 'post_id'
        ]);
        $this->belongsTo('AuthorRetweets', [
            'className' => 'Users',
            'foreignKey' => 'author_id'
        ]);
        $this->hasMany('CountRetweets', [
            'className' => 'Posts',
            'foreignKey' => 'post_id',
            'conditions' =>
                ['CountRetweets.is_deleted' => '0']
        ]);
        $this->hasMany('Comments')
            ->setForeignKey('post_id')
            ->setDependent(true)
            ->setConditions(['Comments.is_deleted' => 0]);
        $this->hasMany('Likes')
            ->setForeignKey('post_id')
            ->setConditions(['Likes.status' => 1]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmptyString('content')
            ->add('content', 'length', [
                'rule' => ['maxLength', '140'],
                'message' => 'Tweet must not be more than 140 characters'
            ])
            ->allowEmpty('image')
            ->add('image', [
                'validExtension' => [
                    'rule' => ['extension', ['png', 'jpg', 'gif', 'jpeg']],
                    'message' => 'Please only upload images (gif, png, jpg).'
                ],
                'fileSize' => [
                    'rule' => array('fileSize', '<=', '5MB'),
                    'message' => 'Cover image must be less than 5MB.',
                    'allowEmpty' => TRUE,
                ],
            ]);

        return $validator;
    }
}

src/Controller/PostsController.php
<?php
// src/Controller/PostsController.php

namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

/**
 * Posts Controller
 * This controller will render views from Template/Posts/
 *
 * @property App\Model\Entity\Post
 */
class PostsController extends AppController
{

    /**
     * This function is executed before every action in the controller
     * Allows user to add, edit and delete posts
     *
     * @param Event $event
     * @return void
     */
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Paginator');
        // Change layout for Ajax requests
        if ($this->request->is('ajax')) {
            $this->layout = 'ajax';
        }

        $this->Auth->allow('add', 'edit', 'delete', 'search');
    }

    /**
     * Displays the index view as home page
     * Allows user to save text and image
     *
     * @return view posts/index
     */
    public function index()
    {
        $userTable = TableRegistry::getTableLocator()->get('Users');
        // set pagination limit and order
        $this->paginate = [
                'limit' => 4,
                'order' => ['created' => 'desc'],
            ];
        // paginate posts
        $posts = $this->paginate(
            $this->Posts->find('all')
                ->where([
                    'OR' => [ //display own and followed user posts
                        ['followJoin.user_id' => $this->Auth->user('id')],
                        ['Users.id' => $this->Auth->user('id')]
                    ],
                    ['Posts.is_deleted' => 0]
                ])
                ->join([
                    'table' => 'follows',
                    'alias' => 'followJoin',
                    'type' => 'LEFT',
                    'conditions' => ['Posts.user_id = followJoin.following']
                ])
                ->group('Posts.id')
                ->contain([
                    'Comments.AuthorComments',
                    'Users',
                    'AuthorRetweets',
                    'Retweets',
                    'Likes',
                    'CountRetweets'])
        );
        // Get list Following
        $following = $userTable->find('all')
            ->where(['followJoin.user_id' => $this->Auth->user('id')])
            ->join([
                'table' => 'follows',
                'alias' => 'followJoin',
                'type' => 'INNER',
                'conditions' => ['Users.id = followJoin.following'],
            ])
            ->toArray();

        // Get list Followers
        $followers = $userTable->find('all')
            ->where(['followJoin.following' => $this->Auth->user('id')])
            ->join([
                'table' => 'follows',
                'alias' => 'followJoin',
                'type' => 'INNER',
                'conditions' => ['Users.id = followJoin.user_id'],
            ])
            ->toArray();

        // get all comments, get last ID record for ajax add comment
        $commentTable = TableRegistry::getTableLocator()->get('Comments');
        $comment = $commentTable->find('all')
            ->where(['is_deleted' => 0])
            ->orWhere(['is_deleted' => 1])
            ->toArray();

        $this->set(compact('comment', 'posts', 'following', 'followers'));
        $this->set('_serialize', ['posts']);

        $post = $this->Posts->newEntity();
        $this->set(compact('post'));
        $this->request->session()->write('redirect', $this->request->here());

        //save user posts
        if ($this->request->is('post')) { // check type of request
            // check comment author
            $checkUser = $this->Auth->user('id');
            $myId = $this->request->getData('userid');
            // show 403 ForbiddenException if other user try to add comments on other profile
            if ($checkUser != $myId) {
                throw new UnauthorizedException(); // unauthorized access to the resource
            }

            $myPost = $this->request->getData('content');
            $myImage = $this->request->getData('image');

            // check if user inserted a data
            if (!empty($myPost) || !empty($myImage)) {
                $post = $this->Posts->patchEntity($post, $this->request->getData());
                $fileName = '';
                $uploadData = $myImage;
                $filename = basename($uploadData['name']);
                $uploadFolder = WWW_ROOT . 'img';
                $uploadPath = $uploadFolder . DS . 'posts' . DS . $filename;

                if (!empty($myImage['name'])) {
                    $ext = substr(strtolower(strrchr($myImage['name'], '.')), 1); //get the extension
                    $arr_ext = ['jpg', 'jpeg', 'gif', 'png']; //set allowed extensions

                    if (in_array($ext, $arr_ext)) {
                        //save the file to the server after successful save
                        move_uploaded_file($uploadData['tmp_name'], $uploadPath);
                    } else {
                        $this->Flash->error(__('Unable to add your post. Please insert a valid image'));

                        return $this->redirect(['action' => 'index']);
                    }
                }

                $post->user_id = $this->Auth->user('id');
                $post->image = $filename;
                $post->is_deleted = '0';

                if ($this->Posts->save($post)) {
                    $this->Flash->success(__('Your post has been saved.'));

                    return $this->redirect(['action' => 'index']);
                }
                $this->Flash->error(__('Unable to add your post.'));
            } else {
                $this->Flash->error(__('Please insert your tweet first'));
            }
        }

        $this->set('authUser', $userTable->get($this->Auth->user('id')));
        $this->set('post', $post);
    }

    /**
     * Retweet User Post
     *
     * @param int $id Handles request post id to be retweeted
     * @return view posts/retweet
     * @throws \Cake\Network\Exception\NotFoundException When the view file could not
     * be found or \Cake\View\Exception\MissingTemplateException in debug mode.
     */
    public function retweet($id = null)
    {
        $userTable = TableRegistry::getTableLocator()->get('Users');

        //show NotFoundException if id is null
        if (!$id) {
            throw new NotFoundException();
        }

        // find the post and check if exists
        $post = $this->Posts->get($id);
        if (!$post) {
            throw new NotFoundException();
        }
        $posts = $this->Posts->find('all', [
            'conditions' => [
                'AND' => [
                    ['Posts.id' => $id],
                    ['Posts.is_deleted' => 0]
                ]
            ]])
            ->orwhere([
                ['Retweets.is_deleted' => 0], // getting retweeted posts
                ['Retweets.is_deleted' => null]]) // null or 0])
            ->contain(['Retweets', 'Users', 'AuthorRetweets'])
            ->toArray();
        //show NotFoundException if post exist
        if (!$posts) {
            throw new NotFoundException();
        }

        $postId = $post['post_id']; // get id post id of retweeted post
        $postOrigin = $this->Posts->find(
            'all',
            ['conditions' => ['Posts.id' => $postId], ['Posts.author_id' => null]]
        )->toArray();

        $retweet = $this->Posts->newEntity();
        $checkPostOrigin = ((!empty($postOrigin)) ? true : false );

        //check if post or put request
        if ($this->request->is(['post', 'put'])) {
            // check if retweeing post was already retweeted
            if (($checkPostOrigin == false) && (!empty($posts) == true)) {
                //set data to be save from unretweeted posts
                $data = [
                    'user_id' => $this->Auth->user('id'),
                    'post_id' => $id,
                    'content' => $this->request->getData('retweet_content'),
                    'image' => $post['image'],
                    'author_id' => $post['user_id'],
                    'retweet_content' => $post['content'],
                    'is_deleted' => 0
                ];
            } else {
                //set data to be save from retweeted posts
                $data = [
                    'user_id' => $this->Auth->user('id'),
                    'post_id' => $postOrigin[0]['id'],
                    'content' => $this->request->getData('retweet_content'),
                    'image' => $postOrigin[0]['image'],
                    'author_id' => $postOrigin[0]['user_id'],
                    'retweet_content' => $postOrigin[0]['content'],
                    'is_deleted' => 0
                ];
            }
            $post = $this->Posts->patchEntity($retweet, $data);

            // save data
            if ($this->Posts->save($post)) {
                $this->Flash->success(__('Your post has been saved.'));

                // redirect to index or home page
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Unable to add post, Please try again'));
        }
        // get and pass the current logged in user credentials

        $this->set('authUser', $userTable->get($this->Auth->user('id')));
        $this->set(compact('posts'));
    }

    /**
     * Like post function
     *
     * @param int $id // Handles request post id for like post
     * @throws \Cake\Network\Exception\NotFoundException When the view file could not
     * be found or \Cake\View\Exception\MissingTemplateException in debug mode.
     * @return void
     */
    public function like($id = null)
    {
        $this->autoRender = false; // No view to render
        //show NotFoundException if id is null
        if (!$id) {

src/Template/Posts/edit.ctp
<div class="main-section-data">
    <div class="row">
        <div class="col-lg-6 col-md-8 offset-md-3 no-pd">
            <div class="main-ws-sec">
                <div class="posts-section">
                <?php foreach ($posts as $post): ?>
                    <div class="post-bar">
                        <div class="post_topbar">
                            <div class="usy-dt">
                            <?= $this->Html->image("profile/" . h($authUser['image']));?>
                                <div class="usy-name">
                                    <h3>
                                        <?php
                                            $userId = $authUser['id'];
                                            echo $this->Html->link(h($authUser['first_name']). " " . h($authUser['last_name']), [
                                                    'controller' => 'users',
                                                    'action' => 'view',
                                                    $userId
                                                ]);
                                        ?>
                                    </h3>
                                    <span>
                                        <?= h($authUser['username'])?>
                                    </span>
                                </div>
                                <!--/ usy-name -->
                            </div>
                            <!--/ usy-dt -->
                        </div>
                        <!--/ post_topbar -->
                        <div class="post_content">
                            <?php if (isset($post->post_id)) {?>
                                <?= $this->Form->create($post, ['enctype' => 'multipart/form-data']);?>
                                <div class="form-group">
                                    <?= $this->Form->textarea('content', [
                                            'rows' => '2',
                                            'cols' => '100',
                                            'maxlength' => 140,
                                            'class' => 'form-control',
                                            'required' => false,
                                            'value' => $post->content,
                                            'placeholder' => 'Add caption or comment...'
                                        ]);
                                    ?>
                                    <small class="form-text text-muted"  style="float:left;">
                                        <span id="remainingCharacter">140</span>
                                        Character(s) Remaining
                                    </small><br>
                                </div>
                                <!--/ form-group -->
                                <div class="retweet-bar col-md-11 offset-md-1">
                                    <div class="retweet_bar">
                                        <div class="post_topbar">
                                            <div class="usy-dt">
                                                <?= $this->Html->image("profile/" . h($post->author_retweet->image));?>
                                                <div class="usy-name">
                                                    <h6>
                                                    <?php
                                                        $authorId = $post->author_retweet->id;
                                                        echo $this->Html->link(h($post->author_retweet->first_name). " " . h($post->author_retweet->last_name), [
                                                                'controller' => 'users',
                                                                'action' => 'view',
                                                                $authorId
                                                            ]);
                                                    ?>
                                                    </h6>
                                                    <span>
                                                        <i class="fa fa-clock-o"></i>
                                                        <?= $this->Time->format(h($post->retweet->created))?>
                                                    </span>
                                                </div>
                                                <!-- / usy-name -->
                                            </div>
                                            <!-- / usy-dt -->
                                        </div>
                                        <!-- / post_topbar -->
                                        <div class = "post_content" onClick="document.location.href='../posts/view/<?=$post->post_id?>'">
                                            <?php if (empty($post->image)) {
                                                    echo '<p>';
                                                        echo h($post->retweet_content);
                                                    echo '</p>';
                                                } else {
                                                    echo '<p>';
                                                        echo h($post->retweet_content);
                                                    echo '</p>';
                                                    echo $this->Html->image("posts/" . h($post->image));
                                                }?>
                                        </div>
                                        <!-- / post_content -->
                                    </div>
                                    <!-- / retweet-bar-->
                                </div>
                                <!-- / retweet-bar col-md-11 -->
                            <div class="form-group">
                                <?php
                                    echo $this->Form->button('Save',
                                        ['action' => 'edit',
                                        'class'=>'btn btn-primary float-right',
                                        'onclick' => "this.form.submit(); this.disabled=true;"]);
                                    echo $this->Form->end();
                                ?>
                            </div>
                            <?php } else { ?>
                                <?= $this->Form->create($post, ['enctype' => 'multipart/form-data']);?>
                                <div class="form-group">
                                    <label for="content">
                                    <?= $this->Form->textarea('content', [
                                            'rows' => '2',
                                            'cols' => '100',
                                            'maxlength' => 140,
                                            'class' => 'form-control',
                                            'required' => false,
                                            'value' => $post->content,
                                            'placeholder' => 'Add caption or comment...'
                                        ]);
                                    ?>
                                    <small class="form-text text-muted"  style="float:left;">
                                        <span id="remainingCharacter">140</span>
                                            Character(s) Remaining
                                    </small><br>
                                </div>
                                <div class="form-row">
                                    <?php if (isset($post->image)) { ?>
                                        <div class="col form-group">
                                            <?= $this->Form->control('image', [
                                                    'type' => 'file',
                                                    'title' => $post->image,
                                                    'value' => $post->image,
                                                    'label' => false
                                                ])
                                            ?>
                                        </div>
                                        <!--/ col form-group -->
                                    <?php } ?>
                                    <div class="col form-group">
                                        <?php
                                            echo $this->Form->button('Save', [
                                                'action' => 'edit',
                                                'class'=>'btn btn-primary float-right',
                                                'onclick' => "this.form.submit(); this.disabled=true;"
                                                ]);
                                            echo $this->Form->end();
                                        ?>
                                    </div>
                                    <!--/ col form-group -->
                                </div>
                                <!--/ form-row -->
                            <?php } ?>
                        </div>
                        <!--/ post_content -->
                    </div>
                    <!--/ post-bar -->
                    <?php endforeach; ?>
                    <!--/ foreach -->
                </div>
                <!--/ main-section -->
            </div>
            <!--/ main-ws-sec -->
        </div>
        <!--/ col-lg-6 col-md-8 no-pd -->
    </div>
    <!--/ row -->
</div>
<!--/ main-section-data -->